### ISSUE TITLE
Add plugin activation/deactivation logs.

### ISSUE THREAD

**Issue by angelleye** [angelleye/woocommerce-product-addons-variable#4]
Need to add callback logs for activation/deactivation status of domains using the plugin.

[This commit](https://github.com/angelleye/offers-for-woocommerce/commit/eae8777ddae18f2d95ecce9aeb39d16c2a54b6c0) shows you the code for activation and deactivation.  Just need to build that into this plugin using the appropriate hooks.

**Comment by levansy2020** [comment]
Please provide plugin id to commit to your server
