### ISSUE TITLE
WordPress 4.5 Conflict..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/woocommerce-product-addons-variable#8]
User report:  https://www.angelleye.com/support/scp/tickets.php?id=484

>I have been using Woocommerce Variable Product Add-ons Variable Product Extension for 3 weeks and it worked fine. This week, after installing some updates including wordpress core files the plugin has stopped working. It always shows the addon on each variation including those which have activated the "Disable Product addon" option.

**Comment by angelleye** [comment]
@kcppdevelopers go ahead and take a look at this and see if you can get it resolved quickly please.

I think this will be your first time looking at this particular plugin.

**Comment by angelleye** [comment]
@kcppdevelopers Did you ever get a chance to review this?

**Comment by kcppdevelopers** [comment]
I have checked above issue it seems "Disable Product addon" option hide the product addon but when user add product to the cart validation is not passed, 

"NEW Option" (product addon field) is a required field.
